Models/SalesStaff.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deAndrade_Project_II.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesStaff
    {
        public SalesStaff()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Full_Time { get; set; }
        public Nullable<System.DateTime> Hire_Date { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public int Employee_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}

Controllers/SalesStaffController.cs
using deAndrade_Project_II.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace deAndrade_Project_II.Controllers
{
    public class SalesStaffController : Controller
    {
        // List Get: SalesStaff
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult List(string id, int sortBy = 0, bool isDesc = false)
        {
            CompanyEntities context = new CompanyEntities();
            List<SalesStaff> salesStaff;

            switch (sortBy)
            {
                case 1:
                    {
                        salesStaff = isDesc ? context.SalesStaffs.OrderByDescending(s => s.Employee.First_Name + " " + s.Employee.Last_Name).ToList() :
                            context.SalesStaffs.OrderBy(s => s.Employee.First_Name + " " + s.Employee.Last_Name).ToList();
                        break;
                    }
                case 2:
                    {
                        salesStaff = isDesc ? context.SalesStaffs.OrderByDescending(s => s.Full_Time).ToList() :
                            context.SalesStaffs.OrderBy(s => s.Full_Time).ToList();
                        break;
                    }
                case 3:
                    {
                        salesStaff = isDesc ? context.SalesStaffs.OrderByDescending(s => s.Hire_Date).ToList() :
                            context.SalesStaffs.OrderBy(s => s.Hire_Date).ToList();
                        break;
                    }
                case 4:
                    {
                        salesStaff = isDesc ? context.SalesStaffs.OrderByDescending(s => s.Salary).ToList() :
                            context.SalesStaffs.OrderBy(s => s.Salary).ToList();
                        break;
                    }
                case 0:
                default:
                    salesStaff = isDesc ? context.SalesStaffs.OrderByDescending(d => d.Id).ToList() :
                        context.SalesStaffs.OrderBy(d => d.Id).ToList();
                    break;
            }

            if (!string.IsNullOrWhiteSpace(id))
            {
                id = id.Trim().ToLower();

                salesStaff = salesStaff.Where(s =>
                    s.Id.ToString().ToLower().Contains(id) ||
                    (s.Employee.First_Name + " " + s.Employee.Last_Name).ToLower().Contains(id) ||
                    s.Full_Time.ToString().Contains(id) ||
                    s.Hire_Date.ToString().Contains(id) ||
                    s.Salary.ToString().Contains(id)
                ).ToList();
            }

            return View(salesStaff);
        }

        /// Upsert Get: SalesStaff
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Upsert(int id)
        {
            CompanyEntities context = new CompanyEntities();
            SalesStaff salesStaff = context.SalesStaffs.Where(s => s.Id == id).FirstOrDefault();
            List<Employee> employees = context.Employees.Where(e => e.Department.Name.ToUpper() != "SALES").ToList();

            UpsertSalesStaffModel viewModel = new UpsertSalesStaffModel()
            {
                SalesStaff = salesStaff,
                Employees = employees
            };

            return View(viewModel);
        }

        /// Upsert Post: SalesStaff
        /// <summary>
        /// 
        /// </summary>
        [HttpPost]
        public ActionResult Upsert(SalesStaff salesStaff)
        {
            SalesStaff newSalesStaff = salesStaff;
            CompanyEntities context = new CompanyEntities();

            try
            {
                // update
                if (context.SalesStaffs.Where(s => s.Id == salesStaff.Id).Count() > 0)
                {
                    var salesStaffToSave = context.SalesStaffs.Where(s => s.Id == newSalesStaff.Id).ToList()[0];

                    salesStaffToSave.Full_Time = newSalesStaff.Full_Time;
                    salesStaffToSave.Hire_Date = newSalesStaff.Hire_Date;
                    salesStaffToSave.Salary = newSalesStaff.Salary;
                }
                else
                {
                    context.SalesStaffs.Add(newSalesStaff);

                    // get sales department id
                    int salesDepartmentId = (context.Departments.Where(d => d.Name.ToUpper() == "SALES").ToList()[0]).Id;

                    // get employee to update
                    var employeeToSave = context.Employees.Where(e => e.Id == salesStaff.Employee_Id).ToList()[0];

                    // get old department id
                    int oldDepartmentId = employeeToSave.Department_Id;

                    // update employee table -> department id
                    employeeToSave.Department_Id = salesDepartmentId;

                    // get department to update
                    var oldDepartmentToSave = context.Departments.Where(d => d.Id == oldDepartmentId).ToList()[0];
                    oldDepartmentToSave.Num_Employees--;

                    var newDepartmentToSave = context.Departments.Where(d => d.Id == salesDepartmentId).ToList()[0];
                    newDepartmentToSave.Num_Employees++;
                }

                context.SaveChanges();
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return RedirectToAction("List");
        }
    }
}

Views/SalesStaff/List.cshtml
@model List<deAndrade_Project_II.Models.SalesStaff>
@{
    ViewBag.Title = "Sales Staff";
}

<h2>Sales Staff List</h2>

<div id="search" class="">
    <input type="text" id="txtSearch" class="form-control" placeholder="Search">
    <button class="btn btn-default" type="button" onclick="new Company().Search()">Search</button>
</div>

<div id="new-customer" class="">
    <a class="btn btn-default" onclick="new Company().Upsert();">Add new sales staff</a>
</div>

<table class="table table-hover">
    <thead class="thead-light">
        <tr>
            <th><span class="theader">ID</span></th>
            <th><span class="theader">Employee name</span></th>
            <th><span class="theader">Full Time</span></th>
            <th><span class="theader">Hire Date</span></th>
            <th><span class="theader">Salary</span></th>
            <th><span class="theader">Edit</span></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var salestaff in Model)
        {
            <tr>
                <td>@salestaff.Id</td>
                <td>@salestaff.Employee.First_Name @salestaff.Employee.Last_Name</td>
                <td>@(salestaff.Full_Time == true ? "Yes" : "No")</td>
                <td>@salestaff.Hire_Date.Value.ToString("MM/dd/yyyy")</td>
                <td>@salestaff.Salary</td>
                <td onclick="new Company().Upsert(@salestaff.Id)"><span class="fa fa-edit"></span></td>
            </tr>
        }
    </tbody>
</table>

Views/SalesStaff/Upsert.cshtml
@model deAndrade_Project_II.Models.UpsertSalesStaffModel
@{
    ViewBag.Title = "Sales Staff";
}

<h2><span id="title"></span> Sales Staff</h2>

@using (Html.BeginForm("Upsert", "SalesStaff", FormMethod.Post))
{
    @Html.HiddenFor(gm => gm.SalesStaff.Id, new { @class = "form-control" })
    <div class="upsert-container">
        <div class="no-collapsing">
            <div class="form-title">Employee name</div>
            <div class="form-field">
                @if (Model.isNull())
                {
                    <input list="employees" name="" class="form-control" onchange="new Company().getEmployeeId(this);" />
                    <datalist id="employees">
                        @foreach (var employee in Model.Employees)
                        {
                            <option id="@employee.First_Name@employee.Last_Name" data-value="@employee.Id" value="@employee.First_Name @employee.Last_Name"></option>
                        }
                    </datalist>
                    @*<select name="SalesStaff.Employee_Id" class="form-control">
                            @foreach (var employee in Model.Employees)
                            {
                                <option value="@employee.Id">@employee.First_Name @employee.Last_Name</option>
                            }
                        </select>*@
                }
                else
                {
                    <span>@Model.SalesStaff.Employee.First_Name @Model.SalesStaff.Employee.Last_Name</span>
                }

            </div>
        </div>
        @* since datalist can't pass the correct Employee_Id to the POST, I created this input to store that info receiving from getEmployeeId() js method*@
        <input type="hidden" id="Employee_Id" name="SalesStaff.Employee_Id" value="" />

        <div><hr /></div>
        <div class="no-collapsing">
            <div class="form-title">Employment type</div>
            <div class="form-field">
                @Html.RadioButtonFor(gm => gm.SalesStaff.Full_Time, true, new { Checked = "checked" }) Full time&nbsp;&nbsp;&nbsp;
                @Html.RadioButtonFor(gm => gm.SalesStaff.Full_Time, false) Part time
            </div>
        </div>

        <div><hr /></div>
        <div class="no-collapsing">
            <div class="form-title">Hire date</div>
            <div class="form-field">
                @Html.TextBoxFor(gm => gm.SalesStaff.Hire_Date, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control" })
            </div>
        </div>

        <div><hr /></div>
        <div class="no-collapsing">
            <div class="form-title">Salary</div>
            <div class="form-field">
                @Html.TextBoxFor(gm => gm.SalesStaff.Salary, new { @type = "number", @class = "form-control", placeholder = "Salary", @min = "0" })
            </div>
        </div>
    </div>

    if (!Model.isNull())
    {
        <script>
            window.onload = function () {
                new Company().getEmployeeId(@Model.SalesStaff.Employee_Id);
            };
        </script>
    }

    <div class="align-content-center">
        <input type="submit" value="Submit" class="btn btn-default" />
        <input type="button" value="Cancel" onclick="new Company().Back();" class="btn btn-default" />
    </div>
}